version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB:
      POSTGRES_USER: PyMaster_team
      POSTGRES_PASSWORD: PyPyMaster654789
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn pymasters.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres-data:
