"""'Init'

Revision ID: 350c231d0bca
Revises: f361a63a0046
Create Date: 2024-07-22 20:28:43.743583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350c231d0bca'
down_revision: Union[str, None] = 'f361a63a0046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_tags',
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('photo_id', 'tag_id')
    )
    op.add_column('photos', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'tags', ['tag'])
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_column('photos', 'description')
    op.drop_table('photo_tags')
    # ### end Alembic commands ###
